LOAD DATA LOCAL INFILE 'item.csv' INTO TABLE Item FIELDS TERMINATED BY ' -|- ';

LOAD DATA LOCAL INFILE 'itemCategory.csv' INTO TABLE Item FIELDS TERMINATED BY ' -|- ';

LOAD DATA LOCAL INFILE 'bids.csv' INTO TABLE Item FIELDS TERMINATED BY ' -|- ';

LOAD DATA LOCAL INFILE 'user.csv' INTO TABLE Item FIELDS TERMINATED BY ' -|- ';