LOAD DATA LOCAL INFILE 'seller.csv' INTO TABLE Seller FIELDS TERMINATED BY ' -|- ';

LOAD DATA LOCAL INFILE 'bidder.csv' INTO TABLE Bidder FIELDS TERMINATED BY ' -|- ';

LOAD DATA LOCAL INFILE 'item.csv' INTO TABLE Item FIELDS TERMINATED BY ' -|- ';

LOAD DATA LOCAL INFILE 'itemCategory.csv' INTO TABLE ItemCategory FIELDS TERMINATED BY ' -|- ';

LOAD DATA LOCAL INFILE 'bids.csv' INTO TABLE Bid FIELDS TERMINATED BY ' -|- ';
